
server:
  port: 6100

eureka:
  instance:
    hostname: emp.eureka6100.com            #eureka����˵�ʵ������
  client:
    register-with-eureka: false         #false��ʾ����ע������ע���Լ���
    fetch-registry: false               #false��ʾ�Լ��˾���ע�����ģ��ҵ�ְ�����ά������ʵ����������Ҫȥ��������
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #������Eureka Server�����ĵ�ַ��ѯ�����ע�������Ҫ���������ַ����������